### ISSUE TITLE
Make chat filter optional

### ISSUE THREAD

**Issue by Dreamedc2015** [Visual1mpact/Paradox_AntiCheat#16]
Make ChatFilter optional

Why:
- Changes packet type from chat to a json_message iirc
- Breaks other code working with chat messages e.g. https://Github.com/Dreamedc2015/MCBE-DISCORD-BRIDGE
- Not everyone wants a chat filter so make it optional to reduce whats running

How:

- turn line 69 into a configurable option in paradox.js

Fix:
#15

**Comment by Visual1mpact** [comment]
This is a good idea. It's original reason for being implemented is that some special characters that are non ASCII are known for breaking the game. It's believed to only truly cause issues when applied to usernames but I have seen reports saying that it can cause problems in chat as well. So this feature is merely extra precaution. We can definitely make it optional. I'm always for the idea of user control and empowerment. I reviewed your pull request and made a comment there. Once things are resolved we can go from here.

**Comment by Visual1mpact** [comment]
Closing this issue in reference to pr #15 being inadequate in it's current state and no changes being made since the initial request was made.
