### ISSUE TITLE
killaura check b flags

### ISSUE THREAD

**Issue by adgods1** [Visual1mpact/Paradox_AntiCheat#18]
when you kill someone it false flags

**Comment by GlitchyTurtle** [comment]
Who does it flag? Working on it and wanted to check if it flagged the one who got killed.

**Comment by adgods1** [comment]
i think the person who died

**Comment by adgods1** [comment]
![image](https://user-images.githubusercontent.com/98714456/155583722-82c6f90a-56af-443e-a1ba-6160dcf0777a.png)

**Comment by Visual1mpact** [comment]
Just to add to this bug report, it will also flag if you kill yourself with /kill

**Comment by GlitchyTurtle** [comment]
Ah, I found the issue.
