### ISSUE TITLE
anti xray toggle

### ISSUE THREAD

**Issue by adgods1** [Visual1mpact/Paradox_AntiCheat#19]
sometimes it spams chat if you have a full server

**Comment by Visual1mpact** [comment]
This was something on my mind when I added it. I plan to handle it when I get around to redoing the menu and modules.

**Comment by Visual1mpact** [comment]
Done in commits 8df85c9de87ef9c5917dfb1d1888cd2aea8f253e and 9495e575c061b4a7a27887b50557705bf5225046

It is enabled by default. You can modify config.js if you wish to make the change permanent between server reboots or you can leave it as is. You can toggle it on or off while in the world using the command ```!xraya```. Toggling it on and off will not persist between server reboots.
