### ISSUE TITLE
Flag Report (broken) // Commands Not Working

### ISSUE THREAD

**Issue by MinerMends** [Visual1mpact/Paradox_AntiCheat#21]
**Describe the bug**
New commits with the flag change completely broke commands: !phase, !antikb, etc
New commits with the flag change completely broke staff notifications (receiving them)
Tested: Anticheat itself is not working (Anti-Phase, Anti-KBm etc)
Normal commands do work though.

**To Reproduce**
1. Type !phase and you'll get an idea.

**Comment by Visual1mpact** [comment]
Fixed  in 6ab75fb943d5a75066a997e6cc526ccf413d01e6
