### ISSUE TITLE
Modules still gets reset when everyone left a realm

### ISSUE THREAD

**Issue by Dylanomeneer** [Visual1mpact/Paradox_AntiCheat#24]
Modules that i have turned off/on will revert back when everyone has left the world

A bonus bug is that all you're tags get randomly removed can't really find a reason

The home system works correctly but when you lose all you're tags you also lose you're home etc

**Comment by SortingFarmer** [comment]
Yea that isnt something Visual can fix (as of rn) as its the realm witch does that to try to clear out space
(But u can perma set the modules state in the config file)

**Comment by adgods1** [comment]
> Modules that i have turned off/on will revert back when everyone has left the world
> 
> A bonus bug is that all you're tags get randomly removed can't really find a reason
> 
> The home system works correctly but when you lose all you're tags you also lose you're home etc

this is prob something with your realm cuz i tested it on a old realm i it doesnt do that

**Comment by Dylanomeneer** [comment]
My realm is 1.18.31 and the world is too

**Comment by Visual1mpact** [comment]
The modules are hardcoded in a file called config.js. When you reset the realm, or turn it off then back on, Paradox will read the information from that file to preset the module settings. However, I made it possible to change those settings while in the world but those changes are only temporary. If you want the changes to persist then you need to modify the file.
