### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by OldGreggo5081** [Visual1mpact/Paradox_AntiCheat#25]
**Describe the bug**
The realm crashes every time

**To Reproduce**
1. Go into a realm with the anti-cheat applied.
2. Open up chat.
3. Type .crash

**Expected behavior**
Realm crashes instantly with no word or warning.

**Comment by Turkeii** [comment]
hi i also seem to be crashing whenever someone times alahkazam in chat its very peculiar

**Comment by adgods1** [comment]
> 

tf are you here
