### ISSUE TITLE
Anti cheat doesn't work on 1.18 versions 

### ISSUE THREAD

**Issue by Dylanomeneer** [Visual1mpact/Paradox_AntiCheat#27]
Hello the anti cheat is broken is there a quick fix that doesn't require waiting for a new update?

**Comment by GlitchyTurtle** [comment]
Yes. Some things will still break, but for the most part, it will fix it. 
Go to the manifest and change `javascript` to `script`. You can find it in modules: `"type": "script",`

**Comment by Visual1mpact** [comment]
All Gametest packs broke with the 1.19 update.
