### ISSUE TITLE
How to op people without going into the files

### ISSUE THREAD

**Issue by Dylanomeneer** [Visual1mpact/Paradox_AntiCheat#28]
So is there an easy way to op urself (i think you can do it with tags) but I'm not sure what it is, or do i require to go into the files and change things

**Comment by SortingFarmer** [comment]
No you need to set the password in the config file and then do !op <password> couse visual has implemented a new system where tags are not needed for security purposes

**Comment by Dylanomeneer** [comment]
Thank you, but is there also a reason why the op command wouldn't work since i did it but still wouldn't get opped

**Comment by Visual1mpact** [comment]
If you are referring to the function command for op then its obsolete. That won't grant you full access to Paradox.

**Comment by Visual1mpact** [comment]
!op password

**Comment by Dylanomeneer** [comment]
I'll explain it a bit more 

I currently have a password by sector encryption but when i use the command: !op (my-password) it doesn't work (does there need to stand true Infront of encryption cuz there isn't) or does something need to be turned on to true that isn't yet

**Comment by Visual1mpact** [comment]
Just now reading your last reply. Nothing needs to be turned on. Just have to include a password in-between the quotes, save the change, then add the edited file back to the pack. Once it's imported to the world you should be able to execute the command followed by the password you set. The only two issues that come to mind which would cause it to not work is the pack being incorrectly modified or the password having a space in it.

**Comment by Dylanomeneer** [comment]
![Screenshot_20220613-162817-043](https://user-images.githubusercontent.com/82913199/173376984-84d16d82-6e98-43f4-95cb-0195edc1c70c.png)
So this is what I have (password was different and no spaces) but if i type "!op hidev" it would not work and give me a error message that I'm not a op. All other features etc works fine

**Comment by Dylanomeneer** [comment]
I just did !op without password and i got opped

**Comment by Visual1mpact** [comment]
Can you send me your mcpack so I can review it?

**Comment by Dylanomeneer** [comment]
[Paradox_AntiCheat-2.17.51.zip](https://github.com/Visual1mpact/Paradox_AntiCheat/files/8894148/Paradox_AntiCheat-2.17.51.zip)

**Comment by Visual1mpact** [comment]
[Paradox-AntiCheat-v2.17.51.zip](https://github.com/Visual1mpact/Paradox_AntiCheat/files/8898907/Paradox-AntiCheat-v2.17.51.zip)

This works. Tested and confirmed.
