### ISSUE TITLE
like every command throws an error if you dont give args

### ISSUE THREAD

**Issue by titushm** [Visual1mpact/Paradox_AntiCheat#41]
like every command throws an error if you dont give args

**Comment by Visual1mpact** [comment]
You are going to need to provide a better report then just that. This doesn't really explain the situation. It just tells me potential user error right now.

**Comment by titushm** [comment]
Not really tho, run just "!sethome" and have the creator error logs on

**Comment by Visual1mpact** [comment]
Ah, see what you mean. Minor issue. I will get that resolved.

Lacking something like this in the code for that specific command. I see there are some others where I forgot to do the same.

```js
    // Are there arguements
    if (!args.length) {
        return goHomeHelp(player, prefix);
    }
```

**Comment by Visual1mpact** [comment]
Fixed in commit https://github.com/Visual1mpact/Paradox_AntiCheat/commit/8595e93075c50d21a6f666ab4b1f8e09bdee2e10
