### ISSUE TITLE
No Funciona en Minecraft 1.19.30

### ISSUE THREAD

**Issue by Bibiautica** [Visual1mpact/Paradox_AntiCheat#47]
Me gusta mucho este complemento, pero para la nueva vercion 1.19.30 no funciona, me gustaria saber cuándo estara disponible la nueva vercion. Muchas gracias, admiro su trabajo.

**Comment by GlitchyTurtle** [comment]
I am sorry for the wait! The update will be coming out soon, and will fix this issue.

I’ll keep this bug report open until I release the new version!

**Comment by GlitchyTurtle** [comment]
I’ll see if I can fix that! It might take a day or two, I’ll reply if I can’t!

**Comment by Bibiautica** [comment]
Espero funcione pronto muchas gracias.

**Comment by Freezefire3** [comment]
Hey just checking in. How is fixing this going? I really love this anticheat and would love to have it working again on my server soon

**Comment by Visual1mpact** [comment]
Check over at https://github.com/frostice482/Paradox_AntiCheat

This particular repo is sorta archived at the moment. Frost has made some subtle updates to get it working with the lastest Minecraft release for now.
