### ISSUE TITLE
Boat or villager click not work

### ISSUE THREAD

**Issue by GabBiswajit** [Visual1mpact/Paradox_AntiCheat#52]
No Options Show Like Boat And Villager Trade
![Uploading Screenshot_2023-06-30-17-46-43-17_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

**Comment by Visual1mpact** [comment]
https://github.com/Pete9xi/Paradox_AntiCheat

Please refer to the repository in the link above as this particular one is not actively maintained anymore.
